name: whatsapp
description: "WhatsApp"
version: 2.0.0
publish_to: 'none'

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  process_run: ^1.1.0
  shared_preferences: ^2.3.2
  tray_manager: ^0.2.3
  webview_win_floating: ^2.2.8
  window_manager: ^0.3.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - images/icon.ico
    - scripts/restartApp.ps1